name: Release .osk

on:
  push:
    tags:
      - 'v*'

jobs:
  release-osk:
    name: Release .osk
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .osk
        run:  git archive --output='./!x.osk' --format=zip HEAD
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '!x.osk'
          makeLatest: true
          generateReleaseNotes: true